const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}})}
function chartEnvelope(bars,meta={}){const a=[...bars].filter(b=>b&&Number.isFinite(+b.open)&&Number.isFinite(+b.high)&&Number.isFinite(+b.low)&&Number.isFinite(+b.close)&&b.openTime).sort((x,y)=>Date.parse(x.openTime)-Date.parse(y.openTime));return {chart:{result:[{meta:{symbol:"XAUUSD",...meta},timestamp:a.map(b=>Math.floor(Date.parse(b.openTime)/1000)),indicators:{quote:[{open:a.map(b=>+b.open),high:a.map(b=>+b.high),low:a.map(b=>+b.low),close:a.map(b=>+b.close),volume:a.map(b=>+(b.tickVolume??b.volume??0))}]}}],error:null}}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
if(url.pathname==='/api/xauusd'){
 const interval=['5m','15m','30m','1h','4h'].includes(url.searchParams.get('interval'))?url.searchParams.get('interval'):'15m';
 const fresh=url.searchParams.get('fresh')||Date.now();
 try{const u=new URL(`https://biquote.io/api/XAUUSD/ohlc`);u.searchParams.set('interval',interval);u.searchParams.set('limit','1000');u.searchParams.set('fresh',fresh);const r=await fetch(u,{headers:{Accept:'application/json'},cf:{cacheTtl:5,cacheEverything:false}});if(r.ok){const d=await r.json();const bars=Array.isArray(d?.bars)?d.bars:[];if(bars.length>=40){let price=null,change=null;try{const t=await fetch(`https://biquote.io/api/XAUUSD?fresh=${fresh}`,{headers:{Accept:'application/json'},cf:{cacheTtl:5,cacheEverything:false}});if(t.ok){const q=await t.json();price=Number.isFinite(+q.mid)?+q.mid:null;change=Number.isFinite(+q.dayDiffPercent)?+q.dayDiffPercent:null}}catch(e){}return json(chartEnvelope(bars,{regularMarketPrice:price??+bars[0].close,regularMarketChangePercent:change,source:'Biquote MT5 XAUUSD'}))}}}catch(e){}
 const yahooInterval=interval==='4h'?'1h':interval;const range=['5m','15m','30m'].includes(yahooInterval)?'1mo':'6mo';for(const host of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{const u=new URL(`https://${host}/v8/finance/chart/XAUUSD=X`);u.searchParams.set('interval',yahooInterval);u.searchParams.set('range',range);u.searchParams.set('includePrePost','false');u.searchParams.set('events','history');const r=await fetch(u,{headers:{Accept:'application/json'}});if(r.ok){const text=await r.text();return new Response(text,{status:200,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}})}}catch(e){}}
 return json({error:'upstream_unavailable',message:'Flux XAU/USD indisponible. Moteur verrouillé sur ATTENDRE.'},502)}
if(url.pathname==='/smart-gold-v10-pro-macd'||url.pathname==='/smart-gold-v10-pro-macd/')return env.ASSETS.fetch(new Request(new URL('/smart-gold-v10-pro-macd.html',request.url),request));
return env.ASSETS.fetch(request)}};